/**
 * Optimized WebP variants generated by `pnpm optimize:images`
 * (scripts/optimizeBellImages.ts). Falls back to the original URL for
 * any image outside public/bells/images.
 */
/** Must stay in sync with SOURCE_PATTERN in scripts/optimizeBellImages.ts. */
const BELL_IMAGE_PATTERN =
	/^(\/bells\/images\/)([^/]+)\.(png|jpe?g|webp|gif)$/i;

function variantUrl(imageUrl: string | undefined, dir: string) {
	if (!imageUrl) return imageUrl;
	const match = imageUrl.match(BELL_IMAGE_PATTERN);
	if (!match) return imageUrl;
	return `${match[1]}${dir}/${match[2]}.webp`;
}

/** 120px-wide thumbnail for list rows (40px display slot). */
export function getBellThumbUrl(imageUrl: string | undefined) {
	return variantUrl(imageUrl, "thumbs");
}

/** 800px-wide image for popup/sidebar headers. */
export function getBellMediumUrl(imageUrl: string | undefined) {
	return variantUrl(imageUrl, "medium");
}
